### ISSUE TITLE
Wegen der Namen

### ISSUE THREAD

**Issue by sgse** [HerrDierk/ArtworkLinux#1]
"That's because when I'm started the wallpaper I had something with Tux inmind, but it turned out very different, haha. Sorry for that."

**So gann isch ned arbeide ;-)**

Gruß
SGS

![g4952](https://user-images.githubusercontent.com/17575778/38305184-36db10fa-380c-11e8-8e6e-1626f50534e3.png)

**Comment by HerrDierk** [comment]
If I'll find the time, I will change the names :-) (those who are wrong)

**Comment by sgse** [comment]
Ich scherze nur, gute Idee, hier die Werke ab zu legen.
